import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/src/components/Header'
import Hero from '@/src/components/Hero'
import About from '@/src/components/About'
import Contact from '@/src/components/Contact'
import HomePage from "./HomePage"
import {motion} from "framer-motion"
import { useRef } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  

  return (
    <motion.div className='h-screen overflow-y-scroll snap-mandatory snap-y'>
      <Head>
        <title>Text Cam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div >
        <HomePage />
      </div>
    </motion.div>
  )
}
