import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/src/components/Header'
import Hero from '@/src/components/Hero'
import About from '@/src/components/About'
import Contact from '@/src/components/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Text Cam</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section id=''>
          <Header />
        </section>
        <section id='/'>
          <Hero />
        </section>
        <section id='about'>
          <About />
        </section>
        <section id='contact'>
          <Contact />
        </section>
        
      </main>
    </>
  )
}
